apiVersion: v1
kind: Pod
metadata:
    name: client
    labels:
        app: client
spec:
  containers:
  - name: server
    image: gowtham4/client:v1
    ports:
    - containerPort: 8180
    env:
    - name: URL
      value: "app-service"
