apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: gowtham4/server:v4
        ports:
        - containerPort: 8180
        tty: true
        stdin: true

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 8180
    targetPort: 8180
    nodePort: 30005
